services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Usada para enviar e receber mensagem entre microserviços
      - "15672:15672" # Usada para acessar a interface de gerenciamento do RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    
volumes:
  rabbitmq_data: