# Variables
@baseUrl = http://localhost:3333

# Health Check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de Testes",
    "description": "Essa é uma sala de testes"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomsQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/a097e219-8796-4e31-a22e-8918339f4792/questions
Content-Type: application/json

{
    "question": "O que é Vue.js e a sua diferença em relação ao Angular ?"
}
